//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace SF1601.Fjernprint
{

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute("ForsendelseI", Namespace = "urn:oio:fjernprint:1.0.0", IsNullable = false)]
    public partial class ForsendelseIType
    {

        private string afsendelseIdentifikatorField;

        private string forsendelseTypeIdentifikatorField;

        private ForsendelseModtagerType forsendelseModtagerField;

        private string filformatNavnField;

        private byte[] meddelelseIndholdDataField;

        private TransaktionsParametreIType transaktionsParametreIField;

        private DokumentParametreType dokumentParametreField;

        private KanalUafhaengigeParametreIType kanalUafhaengigeParametreIField;

        private PrintParametreType printParametreField;

        private DigitalPostParametreType digitalPostParametreField;

        private PostParametreType postParametreField;

        private BilagType[] bilagSamlingField;

        /// <remarks/>
        public string AfsendelseIdentifikator
        {
            get
            {
                return this.afsendelseIdentifikatorField;
            }
            set
            {
                this.afsendelseIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string ForsendelseTypeIdentifikator
        {
            get
            {
                return this.forsendelseTypeIdentifikatorField;
            }
            set
            {
                this.forsendelseTypeIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public ForsendelseModtagerType ForsendelseModtager
        {
            get
            {
                return this.forsendelseModtagerField;
            }
            set
            {
                this.forsendelseModtagerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public string FilformatNavn
        {
            get
            {
                return this.filformatNavnField;
            }
            set
            {
                this.filformatNavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0", DataType = "base64Binary")]
        public byte[] MeddelelseIndholdData
        {
            get
            {
                return this.meddelelseIndholdDataField;
            }
            set
            {
                this.meddelelseIndholdDataField = value;
            }
        }

        /// <remarks/>
        public TransaktionsParametreIType TransaktionsParametreI
        {
            get
            {
                return this.transaktionsParametreIField;
            }
            set
            {
                this.transaktionsParametreIField = value;
            }
        }

        /// <remarks/>
        public DokumentParametreType DokumentParametre
        {
            get
            {
                return this.dokumentParametreField;
            }
            set
            {
                this.dokumentParametreField = value;
            }
        }

        /// <remarks/>
        public KanalUafhaengigeParametreIType KanalUafhaengigeParametreI
        {
            get
            {
                return this.kanalUafhaengigeParametreIField;
            }
            set
            {
                this.kanalUafhaengigeParametreIField = value;
            }
        }

        /// <remarks/>
        public PrintParametreType PrintParametre
        {
            get
            {
                return this.printParametreField;
            }
            set
            {
                this.printParametreField = value;
            }
        }

        /// <remarks/>
        public DigitalPostParametreType DigitalPostParametre
        {
            get
            {
                return this.digitalPostParametreField;
            }
            set
            {
                this.digitalPostParametreField = value;
            }
        }

        /// <remarks/>
        public PostParametreType PostParametre
        {
            get
            {
                return this.postParametreField;
            }
            set
            {
                this.postParametreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Bilag", IsNullable = false)]
        public BilagType[] BilagSamling
        {
            get
            {
                return this.bilagSamlingField;
            }
            set
            {
                this.bilagSamlingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class ForsendelseModtagerType
    {

        private SlutbrugerIdentitetType afsendelseModtagerField;

        private KontaktOplysningType modtagerAdresseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public SlutbrugerIdentitetType AfsendelseModtager
        {
            get
            {
                return this.afsendelseModtagerField;
            }
            set
            {
                this.afsendelseModtagerField = value;
            }
        }

        /// <remarks/>
        public KontaktOplysningType ModtagerAdresse
        {
            get
            {
                return this.modtagerAdresseField;
            }
            set
            {
                this.modtagerAdresseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:dkal:1.0.0")]
    public partial class SlutbrugerIdentitetType
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CPRnummerIdentifikator", typeof(string), Namespace = "urn:oio:adir:dagpenge:2009.07.01")]
        [System.Xml.Serialization.XmlElementAttribute("CVRnummerIdentifikator", typeof(string), Namespace = "urn:oio:adir:dagpenge:2009.07.01")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:dkal:1.0.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oio:adir:dagpenge:2009.07.01:CPRnummerIdentifikator")]
        CPRnummerIdentifikator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oio:adir:dagpenge:2009.07.01:CVRnummerIdentifikator")]
        CVRnummerIdentifikator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class BilagType
    {

        private string bilagNavnField;

        private string filformatNavnField;

        private string bilagSorteringsIndeksIdentifikatorField;

        private object[] itemsField;

        private ItemsChoiceType1[] itemsElementNameField;

        /// <remarks/>
        public string BilagNavn
        {
            get
            {
                return this.bilagNavnField;
            }
            set
            {
                this.bilagNavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public string FilformatNavn
        {
            get
            {
                return this.filformatNavnField;
            }
            set
            {
                this.filformatNavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string BilagSorteringsIndeksIdentifikator
        {
            get
            {
                return this.bilagSorteringsIndeksIdentifikatorField;
            }
            set
            {
                this.bilagSorteringsIndeksIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BilagIdentifikator", typeof(string), Namespace = "urn:oio:dkal:1.0.0")]
        [System.Xml.Serialization.XmlElementAttribute("VedhaeftningIndholdData", typeof(byte[]), Namespace = "urn:oio:dkal:1.0.0", DataType = "base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("VedhaeftningIndholdURLreference", typeof(string), Namespace = "urn:oio:dkal:1.0.0", DataType = "anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("VedhaeftSomIndholdDataIndikator", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oio:dkal:1.0.0:BilagIdentifikator")]
        BilagIdentifikator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oio:dkal:1.0.0:VedhaeftningIndholdData")]
        VedhaeftningIndholdData,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oio:dkal:1.0.0:VedhaeftningIndholdURLreference")]
        VedhaeftningIndholdURLreference,

        /// <remarks/>
        VedhaeftSomIndholdDataIndikator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class PostParametreType
    {

        private PostKategoriKodeType postKategoriKodeField;

        private bool postKategoriKodeFieldSpecified;

        private string allokeringsIdentifikatorField;

        private bool returposthaandteringHosLeverandoerIndikatorField;

        private bool returposthaandteringHosLeverandoerIndikatorFieldSpecified;

        private bool informationVedAdresseAendringIndikatorField;

        private bool informationVedAdresseAendringIndikatorFieldSpecified;

        private string sideKvantitetField;

        /// <remarks/>
        public PostKategoriKodeType PostKategoriKode
        {
            get
            {
                return this.postKategoriKodeField;
            }
            set
            {
                this.postKategoriKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostKategoriKodeSpecified
        {
            get
            {
                return this.postKategoriKodeFieldSpecified;
            }
            set
            {
                this.postKategoriKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string AllokeringsIdentifikator
        {
            get
            {
                return this.allokeringsIdentifikatorField;
            }
            set
            {
                this.allokeringsIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public bool ReturposthaandteringHosLeverandoerIndikator
        {
            get
            {
                return this.returposthaandteringHosLeverandoerIndikatorField;
            }
            set
            {
                this.returposthaandteringHosLeverandoerIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturposthaandteringHosLeverandoerIndikatorSpecified
        {
            get
            {
                return this.returposthaandteringHosLeverandoerIndikatorFieldSpecified;
            }
            set
            {
                this.returposthaandteringHosLeverandoerIndikatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool InformationVedAdresseAendringIndikator
        {
            get
            {
                return this.informationVedAdresseAendringIndikatorField;
            }
            set
            {
                this.informationVedAdresseAendringIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InformationVedAdresseAendringIndikatorSpecified
        {
            get
            {
                return this.informationVedAdresseAendringIndikatorFieldSpecified;
            }
            set
            {
                this.informationVedAdresseAendringIndikatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string SideKvantitet
        {
            get
            {
                return this.sideKvantitetField;
            }
            set
            {
                this.sideKvantitetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum PostKategoriKodeType
    {

        /// <remarks/>
        Prioritaire,

        /// <remarks/>
        Economique,

        /// <remarks/>
        Bulk,

        /// <remarks/>
        Rekommanderet,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Rekommanderet med modtagerbevis")]
        Rekommanderetmedmodtagerbevis,

        /// <remarks/>
        Forkyndelse,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:dkal:1.0.0")]
    public partial class MeddelelseFESDmetadataType
    {

        private string fESDdokumentIdentifikatorField;

        private string fESDaktoerIdentifikatorField;

        private string fESDsagIdentifikatorField;

        private string fESDsagsklassifikationIdentifikatorField;

        /// <remarks/>
        public string FESDdokumentIdentifikator
        {
            get
            {
                return this.fESDdokumentIdentifikatorField;
            }
            set
            {
                this.fESDdokumentIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string FESDaktoerIdentifikator
        {
            get
            {
                return this.fESDaktoerIdentifikatorField;
            }
            set
            {
                this.fESDaktoerIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string FESDsagIdentifikator
        {
            get
            {
                return this.fESDsagIdentifikatorField;
            }
            set
            {
                this.fESDsagIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public string FESDsagsklassifikationIdentifikator
        {
            get
            {
                return this.fESDsagsklassifikationIdentifikatorField;
            }
            set
            {
                this.fESDsagsklassifikationIdentifikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class DigitalPostParametreType
    {

        private System.DateTime afsendelseDatoTidField;

        private bool afsendelseDatoTidFieldSpecified;

        private string meddelelseIndholdstypeIdentifikatorField;

        private MeddelelseSvarTypeNavnType meddelelseSvarTypeNavnField;

        private bool meddelelseSvarTypeNavnFieldSpecified;

        private string meddelelseSvarPostkasseIdentifikatorField;

        private string meddelelseSvarEmneIdentifikatorField;

        private MeddelelseFESDmetadataType meddelelseFESDmetadataField;

        private bool medsendDokumentRegistreringIndikatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public System.DateTime AfsendelseDatoTid
        {
            get
            {
                return this.afsendelseDatoTidField;
            }
            set
            {
                this.afsendelseDatoTidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AfsendelseDatoTidSpecified
        {
            get
            {
                return this.afsendelseDatoTidFieldSpecified;
            }
            set
            {
                this.afsendelseDatoTidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0", DataType = "nonNegativeInteger")]
        public string MeddelelseIndholdstypeIdentifikator
        {
            get
            {
                return this.meddelelseIndholdstypeIdentifikatorField;
            }
            set
            {
                this.meddelelseIndholdstypeIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public MeddelelseSvarTypeNavnType MeddelelseSvarTypeNavn
        {
            get
            {
                return this.meddelelseSvarTypeNavnField;
            }
            set
            {
                this.meddelelseSvarTypeNavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeddelelseSvarTypeNavnSpecified
        {
            get
            {
                return this.meddelelseSvarTypeNavnFieldSpecified;
            }
            set
            {
                this.meddelelseSvarTypeNavnFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0", DataType = "nonNegativeInteger")]
        public string MeddelelseSvarPostkasseIdentifikator
        {
            get
            {
                return this.meddelelseSvarPostkasseIdentifikatorField;
            }
            set
            {
                this.meddelelseSvarPostkasseIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0", DataType = "nonNegativeInteger")]
        public string MeddelelseSvarEmneIdentifikator
        {
            get
            {
                return this.meddelelseSvarEmneIdentifikatorField;
            }
            set
            {
                this.meddelelseSvarEmneIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:dkal:1.0.0")]
        public MeddelelseFESDmetadataType MeddelelseFESDmetadata
        {
            get
            {
                return this.meddelelseFESDmetadataField;
            }
            set
            {
                this.meddelelseFESDmetadataField = value;
            }
        }

        /// <remarks/>
        public bool MedsendDokumentRegistreringIndikator
        {
            get
            {
                return this.medsendDokumentRegistreringIndikatorField;
            }
            set
            {
                this.medsendDokumentRegistreringIndikatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:dkal:1.0.0")]
    public enum MeddelelseSvarTypeNavnType
    {

        /// <remarks/>
        angivet,

        /// <remarks/>
        ikkeMuligt,

        /// <remarks/>
        standard,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class PrintParametreType
    {

        private SimplexDuplexKodeType simplexDuplexKodeField;

        private bool simplexDuplexKodeFieldSpecified;

        private FarveSHKodeType farveSHKodeField;

        private bool farveSHKodeFieldSpecified;

        private KuvertTypeKodeType kuvertTypeKodeField;

        private bool kuvertTypeKodeFieldSpecified;

        /// <remarks/>
        public SimplexDuplexKodeType SimplexDuplexKode
        {
            get
            {
                return this.simplexDuplexKodeField;
            }
            set
            {
                this.simplexDuplexKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SimplexDuplexKodeSpecified
        {
            get
            {
                return this.simplexDuplexKodeFieldSpecified;
            }
            set
            {
                this.simplexDuplexKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public FarveSHKodeType FarveSHKode
        {
            get
            {
                return this.farveSHKodeField;
            }
            set
            {
                this.farveSHKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FarveSHKodeSpecified
        {
            get
            {
                return this.farveSHKodeFieldSpecified;
            }
            set
            {
                this.farveSHKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public KuvertTypeKodeType KuvertTypeKode
        {
            get
            {
                return this.kuvertTypeKodeField;
            }
            set
            {
                this.kuvertTypeKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KuvertTypeKodeSpecified
        {
            get
            {
                return this.kuvertTypeKodeFieldSpecified;
            }
            set
            {
                this.kuvertTypeKodeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum SimplexDuplexKodeType
    {

        /// <remarks/>
        Simplex,

        /// <remarks/>
        Duplex,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum FarveSHKodeType
    {

        /// <remarks/>
        SH,

        /// <remarks/>
        Farve,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum KuvertTypeKodeType
    {

        /// <remarks/>
        C4,

        /// <remarks/>
        C5,

        /// <remarks/>
        MA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class ForsendelseAfsenderType
    {

        private KontaktOplysningType afsenderAdresseField;

        /// <remarks/>
        public KontaktOplysningType AfsenderAdresse
        {
            get
            {
                return this.afsenderAdresseField;
            }
            set
            {
                this.afsenderAdresseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class KontaktOplysningType
    {

        private string personNameField;

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private CountryIdentificationCodeType countryIdentificationCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/")]
        public string PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FloorIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        [System.Xml.Serialization.XmlElementAttribute("MailDeliverySublocationIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        [System.Xml.Serialization.XmlElementAttribute("StreetBuildingIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        [System.Xml.Serialization.XmlElementAttribute("SuiteIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        [System.Xml.Serialization.XmlElementAttribute("DistrictSubdivisionIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        [System.Xml.Serialization.XmlElementAttribute("PostCodeIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        [System.Xml.Serialization.XmlElementAttribute("StreetName", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        [System.Xml.Serialization.XmlElementAttribute("PostOfficeBoxIdentifier", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/", DataType = "integer")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressFifthLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressFirstLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressFourthLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressSecondLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressSixthLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("PostalAddressThirdLineText", typeof(string), Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/")]
        [System.Xml.Serialization.XmlElementAttribute("CoNavn", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public CountryIdentificationCodeType CountryIdentificationCode
        {
            get
            {
                return this.countryIdentificationCodeField;
            }
            set
            {
                this.countryIdentificationCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/:FloorIdentifier")]
        FloorIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/:MailDeliverySublocationIdent" +
            "ifier")]
        MailDeliverySublocationIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/:StreetBuildingIdentifier")]
        StreetBuildingIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/:SuiteIdentifier")]
        SuiteIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/:DistrictSubdivisionIdentifie" +
            "r")]
        DistrictSubdivisionIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/:PostCodeIdentifier")]
        PostCodeIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/:StreetName")]
        StreetName,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/:PostOfficeBoxIdentifier")]
        PostOfficeBoxIdentifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressFifthLineText")]
        PostalAddressFifthLineText,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressFirstLineText")]
        PostalAddressFirstLineText,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressFourthLineText")]
        PostalAddressFourthLineText,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressSecondLineText")]
        PostalAddressSecondLineText,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressSixthLineText")]
        PostalAddressSixthLineText,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/:PostalAddressThirdLineText")]
        PostalAddressThirdLineText,

        /// <remarks/>
        CoNavn,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType
    {

        private _CountryIdentificationSchemeType schemeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,

        /// <remarks/>
        imk,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class KanalUafhaengigeParametreIType
    {

        private string enhedTekstField;

        private string brugerNavnField;

        private string konteringsGruppeTekstField;

        private ForsendelseAfsenderType forsendelseAfsenderField;

        private bool paatrykAfsenderAdresseIndikatorField;

        private bool paatrykAfsenderAdresseIndikatorFieldSpecified;

        private bool paatrykModtagerAdresseIndikatorField;

        private bool paatrykModtagerAdresseIndikatorFieldSpecified;

        private bool paatrykBrevdatoIndikatorField;

        private bool paatrykBrevdatoIndikatorFieldSpecified;

        private KanalKodeType kanalKodeField;

        private bool kanalKodeFieldSpecified;

        private bool hasteBrevIndikatorField;

        private bool hasteBrevIndikatorFieldSpecified;

        /// <remarks/>
        public string EnhedTekst
        {
            get
            {
                return this.enhedTekstField;
            }
            set
            {
                this.enhedTekstField = value;
            }
        }

        /// <remarks/>
        public string BrugerNavn
        {
            get
            {
                return this.brugerNavnField;
            }
            set
            {
                this.brugerNavnField = value;
            }
        }

        /// <remarks/>
        public string KonteringsGruppeTekst
        {
            get
            {
                return this.konteringsGruppeTekstField;
            }
            set
            {
                this.konteringsGruppeTekstField = value;
            }
        }

        /// <remarks/>
        public ForsendelseAfsenderType ForsendelseAfsender
        {
            get
            {
                return this.forsendelseAfsenderField;
            }
            set
            {
                this.forsendelseAfsenderField = value;
            }
        }

        /// <remarks/>
        public bool PaatrykAfsenderAdresseIndikator
        {
            get
            {
                return this.paatrykAfsenderAdresseIndikatorField;
            }
            set
            {
                this.paatrykAfsenderAdresseIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaatrykAfsenderAdresseIndikatorSpecified
        {
            get
            {
                return this.paatrykAfsenderAdresseIndikatorFieldSpecified;
            }
            set
            {
                this.paatrykAfsenderAdresseIndikatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool PaatrykModtagerAdresseIndikator
        {
            get
            {
                return this.paatrykModtagerAdresseIndikatorField;
            }
            set
            {
                this.paatrykModtagerAdresseIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaatrykModtagerAdresseIndikatorSpecified
        {
            get
            {
                return this.paatrykModtagerAdresseIndikatorFieldSpecified;
            }
            set
            {
                this.paatrykModtagerAdresseIndikatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool PaatrykBrevdatoIndikator
        {
            get
            {
                return this.paatrykBrevdatoIndikatorField;
            }
            set
            {
                this.paatrykBrevdatoIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaatrykBrevdatoIndikatorSpecified
        {
            get
            {
                return this.paatrykBrevdatoIndikatorFieldSpecified;
            }
            set
            {
                this.paatrykBrevdatoIndikatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public KanalKodeType KanalKode
        {
            get
            {
                return this.kanalKodeField;
            }
            set
            {
                this.kanalKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KanalKodeSpecified
        {
            get
            {
                return this.kanalKodeFieldSpecified;
            }
            set
            {
                this.kanalKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool HasteBrevIndikator
        {
            get
            {
                return this.hasteBrevIndikatorField;
            }
            set
            {
                this.hasteBrevIndikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasteBrevIndikatorSpecified
        {
            get
            {
                return this.hasteBrevIndikatorFieldSpecified;
            }
            set
            {
                this.hasteBrevIndikatorFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum KanalKodeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Digital Post")]
        DigitalPost,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fysisk Post")]
        FysiskPost,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class DokumentParametreType
    {

        private string titelTekstField;

        private string uUIDIdentifikatorField;

        private System.DateTime brevDatoField;

        private bool brevDatoFieldSpecified;

        private System.Xml.XmlElement meddelelsesFormatObjektField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string TitelTekst
        {
            get
            {
                return this.titelTekstField;
            }
            set
            {
                this.titelTekstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0")]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oio:sagdok:3.0.0", DataType = "date")]
        public System.DateTime BrevDato
        {
            get
            {
                return this.brevDatoField;
            }
            set
            {
                this.brevDatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrevDatoSpecified
        {
            get
            {
                return this.brevDatoFieldSpecified;
            }
            set
            {
                this.brevDatoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement MeddelelsesFormatObjekt
        {
            get
            {
                return this.meddelelsesFormatObjektField;
            }
            set
            {
                this.meddelelsesFormatObjektField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public partial class TransaktionsParametreIType
    {

        private System.DateTime transaktionsDatoTidField;

        private bool transaktionsDatoTidFieldSpecified;

        private string masseForsendelseIdentifikatorField;

        private KvitteringsTypeKodeType kvitteringsTypeKodeField;

        private bool kvitteringsTypeKodeFieldSpecified;

        private string kvitteringsEmailField;

        /// <remarks/>
        public System.DateTime TransaktionsDatoTid
        {
            get
            {
                return this.transaktionsDatoTidField;
            }
            set
            {
                this.transaktionsDatoTidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaktionsDatoTidSpecified
        {
            get
            {
                return this.transaktionsDatoTidFieldSpecified;
            }
            set
            {
                this.transaktionsDatoTidFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string MasseForsendelseIdentifikator
        {
            get
            {
                return this.masseForsendelseIdentifikatorField;
            }
            set
            {
                this.masseForsendelseIdentifikatorField = value;
            }
        }

        /// <remarks/>
        public KvitteringsTypeKodeType KvitteringsTypeKode
        {
            get
            {
                return this.kvitteringsTypeKodeField;
            }
            set
            {
                this.kvitteringsTypeKodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KvitteringsTypeKodeSpecified
        {
            get
            {
                return this.kvitteringsTypeKodeFieldSpecified;
            }
            set
            {
                this.kvitteringsTypeKodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string KvitteringsEmail
        {
            get
            {
                return this.kvitteringsEmailField;
            }
            set
            {
                this.kvitteringsEmailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oio:fjernprint:1.0.0")]
    public enum KvitteringsTypeKodeType
    {

        /// <remarks/>
        Alle,

        /// <remarks/>
        Ingen,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Kun fejl")]
        Kunfejl,
    }

}