//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace SF1601
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "https://DigitalPost.dk/MeMo-1", IsNullable = false)]


    public partial class Message
    {

        private MessageHeader messageHeaderField;

        private MessageBody messageBodyField;

        private decimal memoVersionField;

        private string memoSchVersionField;

        private string memoattributeField;

        /// <remarks/>
        public MessageHeader MessageHeader
        {
            get
            {
                return this.messageHeaderField;
            }
            set
            {
                this.messageHeaderField = value;
            }
        }

        /// <remarks/>
        public MessageBody MessageBody
        {
            get
            {
                return this.messageBodyField;
            }
            set
            {
                this.messageBodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal memoVersion
        {
            get
            {
                return this.memoVersionField;
            }
            set
            {
                this.memoVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string memoSchVersion
        {
            get
            {
                return this.memoSchVersionField;
            }
            set
            {
                this.memoSchVersionField = value;
            }
        }

        public string memoattribute
        {
            get
            {
                return this.memoattributeField;
            }
            set
            {
                this.memoattributeField = value;
            }
        }


    }

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    ////[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class MessageHeader
    {

        //private memoMessageType messageTypeField;
        private string messageTypeField;

        private string messageUUIDField;

        private string messageIDField;

        private string messageCodeField;

        private string labelField;

        private string notificationField;

        private string additionalNotificationField;

        private bool replyField;

        private System.DateTime replyByDateTimeField;

        private bool replyByDateTimeFieldSpecified;

        private System.DateTime doNotDeliverUntilDateField;

        private bool doNotDeliverUntilDateFieldSpecified;

        private bool mandatoryField;

        private bool legalNotificationField;

        private string postTypeField;

        private Sender senderField;

        private Recipient recipientField;

        private ContentData contentDataField;

        private ForwardData forwardDataField;

        private ReplyData[] replyDataField;

        public MessageHeader()
        {
            this.replyField = false;
            this.mandatoryField = false;
            this.legalNotificationField = false;
        }

        /// <remarks/>
        public string messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }

        /// <remarks/>
        public string messageUUID
        {
            get
            {
                return this.messageUUIDField;
            }
            set
            {
                this.messageUUIDField = value;
            }
        }

        /// <remarks/>
        public string messageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        public string messageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string notification
        {
            get
            {
                return this.notificationField;
            }
            set
            {
                this.notificationField = value;
            }
        }

        /// <remarks/>
        public string additionalNotification
        {
            get
            {
                return this.additionalNotificationField;
            }
            set
            {
                this.additionalNotificationField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool reply
        {
            get
            {
                return this.replyField;
            }
            set
            {
                this.replyField = value;
            }
        }

        /// <remarks/>
        public System.DateTime replyByDateTime
        {
            get
            {
                return this.replyByDateTimeField;
            }
            set
            {
                this.replyByDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyByDateTimeSpecified
        {
            get
            {
                return this.replyByDateTimeFieldSpecified;
            }
            set
            {
                this.replyByDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime doNotDeliverUntilDate
        {
            get
            {
                return this.doNotDeliverUntilDateField;
            }
            set
            {
                this.doNotDeliverUntilDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doNotDeliverUntilDateSpecified
        {
            get
            {
                return this.doNotDeliverUntilDateFieldSpecified;
            }
            set
            {
                this.doNotDeliverUntilDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool mandatory
        {
            get
            {
                return this.mandatoryField;
            }
            set
            {
                this.mandatoryField = value;
            }
        }

        /// <remarks/>
        public bool legalNotification
        {
            get
            {
                return this.legalNotificationField;
            }
            set
            {
                this.legalNotificationField = value;
            }
        }

        /// <remarks/>
        public string postType
        {
            get
            {
                return this.postTypeField;
            }
            set
            {
                this.postTypeField = value;
            }
        }

        /// <remarks/>
        public Sender Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        public Recipient Recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }

        /// <remarks/>
        public ContentData ContentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }

        /// <remarks/>
        public ForwardData ForwardData
        {
            get
            {
                return this.forwardDataField;
            }
            set
            {
                this.forwardDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReplyData")]
        public ReplyData[] ReplyData
        {
            get
            {
                return this.replyDataField;
            }
            set
            {
                this.replyDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://data.gov.dk/model/dataTypes/")]
    public enum memoMessageType
    {

        /// <remarks/>
        DIGITALPOST,

        /// <remarks/>
        NEMSMS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    ////[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class Sender
    {

        private string senderIDField;

        private string idTypeField;

        private string idTypeLabelField;

        private string labelField;

        private AttentionData attentionDataField;

        private ContactPoint contactPointField;

        /// <remarks/>
        public string senderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }

        /// <remarks/>
        public string idType
        {
            get
            {
                return this.idTypeField;
            }
            set
            {
                this.idTypeField = value;
            }
        }

        /// <remarks/>
        public string idTypeLabel
        {
            get
            {
                return this.idTypeLabelField;
            }
            set
            {
                this.idTypeLabelField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public AttentionData AttentionData
        {
            get
            {
                return this.attentionDataField;
            }
            set
            {
                this.attentionDataField = value;
            }
        }

        /// <remarks/>
        public ContactPoint ContactPoint
        {
            get
            {
                return this.contactPointField;
            }
            set
            {
                this.contactPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class AttentionData
    {

        private AttentionPerson attentionPersonField;

        private ProductionUnit productionUnitField;

        private GlobalLocationNumber globalLocationNumberField;

        private EMail eMailField;

        private SEnumber sEnumberField;

        private Telephone telephoneField;

        private EID eIDField;

        private ContentResponsible contentResponsibleField;

        private GeneratingSystem generatingSystemField;

        private SORdata sORdataField;

        private Address addressField;

        private UnstructuredAddress unstructuredAddressField;

        /// <remarks/>
        public AttentionPerson AttentionPerson
        {
            get
            {
                return this.attentionPersonField;
            }
            set
            {
                this.attentionPersonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public ProductionUnit ProductionUnit
        {
            get
            {
                return this.productionUnitField;
            }
            set
            {
                this.productionUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://www.gs1.dk/gs1-standarder/identifikation/gln-global-location-number/")]
        public GlobalLocationNumber GlobalLocationNumber
        {
            get
            {
                return this.globalLocationNumberField;
            }
            set
            {
                this.globalLocationNumberField = value;
            }
        }

        /// <remarks/>
        public EMail EMail
        {
            get
            {
                return this.eMailField;
            }
            set
            {
                this.eMailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public SEnumber SEnumber
        {
            get
            {
                return this.sEnumberField;
            }
            set
            {
                this.sEnumberField = value;
            }
        }

        /// <remarks/>
        public Telephone Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public EID EID
        {
            get
            {
                return this.eIDField;
            }
            set
            {
                this.eIDField = value;
            }
        }

        /// <remarks/>
        public ContentResponsible ContentResponsible
        {
            get
            {
                return this.contentResponsibleField;
            }
            set
            {
                this.contentResponsibleField = value;
            }
        }

        /// <remarks/>
        public GeneratingSystem GeneratingSystem
        {
            get
            {
                return this.generatingSystemField;
            }
            set
            {
                this.generatingSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://services.nsi.dk/en/Services/SOR")]
        public SORdata SORdata
        {
            get
            {
                return this.sORdataField;
            }
            set
            {
                this.sORdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public UnstructuredAddress UnstructuredAddress
        {
            get
            {
                return this.unstructuredAddressField;
            }
            set
            {
                this.unstructuredAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class AttentionPerson
    {

        private string personIDField;

        private string labelField;

        /// <remarks/>
        public string personID
        {
            get
            {
                return this.personIDField;
            }
            set
            {
                this.personIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class ProductionUnit
    {

        private long productionUnitNumberField;

        private string productionUnitNameField;

        /// <remarks/>
        public long productionUnitNumber
        {
            get
            {
                return this.productionUnitNumberField;
            }
            set
            {
                this.productionUnitNumberField = value;
            }
        }

        /// <remarks/>
        public string productionUnitName
        {
            get
            {
                return this.productionUnitNameField;
            }
            set
            {
                this.productionUnitNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.gs1.dk/gs1-standarder/identifikation/gln-global-location-number/")]
    public partial class GlobalLocationNumber
    {

        private long globalLocationNumberField;

        private string locationField;

        /// <remarks/>
        public long globalLocationNumber
        {
            get
            {
                return this.globalLocationNumberField;
            }
            set
            {
                this.globalLocationNumberField = value;
            }
        }

        /// <remarks/>
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class EMail
    {

        private string emailAddressField;

        private string relatedAgentField;

        /// <remarks/>
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        public string relatedAgent
        {
            get
            {
                return this.relatedAgentField;
            }
            set
            {
                this.relatedAgentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class SEnumber
    {

        private string seNumberField;

        private string companyNameField;

        /// <remarks/>
        public string seNumber
        {
            get
            {
                return this.seNumberField;
            }
            set
            {
                this.seNumberField = value;
            }
        }

        /// <remarks/>
        public string companyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class Telephone
    {

        private string telephoneNumberField;

        private string relatedAgentField;

        /// <remarks/>
        public string telephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        public string relatedAgent
        {
            get
            {
                return this.relatedAgentField;
            }
            set
            {
                this.relatedAgentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class EID
    {

        private string eIDField;

        private string labelField;

        /// <remarks/>
        public string eID
        {
            get
            {
                return this.eIDField;
            }
            set
            {
                this.eIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ContentResponsible
    {

        private string contentResponsibleIDField;

        private string labelField;

        /// <remarks/>
        public string contentResponsibleID
        {
            get
            {
                return this.contentResponsibleIDField;
            }
            set
            {
                this.contentResponsibleIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class GeneratingSystem
    {

        private string generatingSystemIDField;

        private string labelField;

        /// <remarks/>
        public string generatingSystemID
        {
            get
            {
                return this.generatingSystemIDField;
            }
            set
            {
                this.generatingSystemIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://services.nsi.dk/en/Services/SOR")]
    public partial class SORdata
    {

        private string sorIdentifierField;

        private string entryNameField;

        /// <remarks/>
        public string sorIdentifier
        {
            get
            {
                return this.sorIdentifierField;
            }
            set
            {
                this.sorIdentifierField = value;
            }
        }

        /// <remarks/>
        public string entryName
        {
            get
            {
                return this.entryNameField;
            }
            set
            {
                this.entryNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class Address
    {

        private string idField;

        private string addressLabelField;

        private string houseNumberField;

        private string doorField;

        private string floorField;

        private string coField;

        private string zipCodeField;

        private string cityField;

        private string countryField;

        private AddressPoint addressPointField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string addressLabel
        {
            get
            {
                return this.addressLabelField;
            }
            set
            {
                this.addressLabelField = value;
            }
        }

        /// <remarks/>
        public string houseNumber
        {
            get
            {
                return this.houseNumberField;
            }
            set
            {
                this.houseNumberField = value;
            }
        }

        /// <remarks/>
        public string door
        {
            get
            {
                return this.doorField;
            }
            set
            {
                this.doorField = value;
            }
        }

        /// <remarks/>
        public string floor
        {
            get
            {
                return this.floorField;
            }
            set
            {
                this.floorField = value;
            }
        }

        /// <remarks/>
        public string co
        {
            get
            {
                return this.coField;
            }
            set
            {
                this.coField = value;
            }
        }

        /// <remarks/>
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public AddressPoint AddressPoint
        {
            get
            {
                return this.addressPointField;
            }
            set
            {
                this.addressPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class AddressPoint
    {

        private string geographicEastingMeasureField;

        private string geographicNorthingMeasureField;

        private string geographicHeightMeasureField;

        /// <remarks/>
        public string geographicEastingMeasure
        {
            get
            {
                return this.geographicEastingMeasureField;
            }
            set
            {
                this.geographicEastingMeasureField = value;
            }
        }

        /// <remarks/>
        public string geographicNorthingMeasure
        {
            get
            {
                return this.geographicNorthingMeasureField;
            }
            set
            {
                this.geographicNorthingMeasureField = value;
            }
        }

        /// <remarks/>
        public string geographicHeightMeasure
        {
            get
            {
                return this.geographicHeightMeasureField;
            }
            set
            {
                this.geographicHeightMeasureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class UnstructuredAddress
    {

        private string unstructuredField;

        /// <remarks/>
        public string unstructured
        {
            get
            {
                return this.unstructuredField;
            }
            set
            {
                this.unstructuredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ContactPoint
    {

        private string contactGroupField;

        private string contactPointIDField;

        private string labelField;

        private ContactInfo[] contactInfoField;

        /// <remarks/>
        public string contactGroup
        {
            get
            {
                return this.contactGroupField;
            }
            set
            {
                this.contactGroupField = value;
            }
        }

        /// <remarks/>
        public string contactPointID
        {
            get
            {
                return this.contactPointIDField;
            }
            set
            {
                this.contactPointIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactInfo")]
        public ContactInfo[] ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ContactInfo
    {

        private string labelField;

        private string valueField;

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class Recipient
    {

        private string recipientIDField;

        private string idTypeField;

        private string idTypeLabelField;

        private string labelField;

        private AttentionData attentionDataField;

        private ContactPoint contactPointField;

        /// <remarks/>
        public string recipientID
        {
            get
            {
                return this.recipientIDField;
            }
            set
            {
                this.recipientIDField = value;
            }
        }

        /// <remarks/>
        public string idType
        {
            get
            {
                return this.idTypeField;
            }
            set
            {
                this.idTypeField = value;
            }
        }

        /// <remarks/>
        public string idTypeLabel
        {
            get
            {
                return this.idTypeLabelField;
            }
            set
            {
                this.idTypeLabelField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public AttentionData AttentionData
        {
            get
            {
                return this.attentionDataField;
            }
            set
            {
                this.attentionDataField = value;
            }
        }

        /// <remarks/>
        public ContactPoint ContactPoint
        {
            get
            {
                return this.contactPointField;
            }
            set
            {
                this.contactPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ContentData
    {

        private CPRdata cPRdataField;

        private CVRdata cVRdataField;

        private MotorVehicle motorVehicleField;

        private PropertyNumber propertyNumberField;

        private CaseID caseIDField;

        private KLEdata kLEdataField;

        private FORMdata fORMdataField;

        private ProductionUnit productionUnitField;

        private Education educationField;

        private Address addressField;

        private UnstructuredAddress unstructuredAddressField;

        private AdditionalContentData[] additionalContentDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public CPRdata CPRdata
        {
            get
            {
                return this.cPRdataField;
            }
            set
            {
                this.cPRdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public CVRdata CVRdata
        {
            get
            {
                return this.cVRdataField;
            }
            set
            {
                this.cVRdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://motorregister.skat.dk/")]
        public MotorVehicle MotorVehicle
        {
            get
            {
                return this.motorVehicleField;
            }
            set
            {
                this.motorVehicleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public PropertyNumber PropertyNumber
        {
            get
            {
                return this.propertyNumberField;
            }
            set
            {
                this.propertyNumberField = value;
            }
        }

        /// <remarks/>
        public CaseID CaseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://kle-online.dk/")]
        public KLEdata KLEdata
        {
            get
            {
                return this.kLEdataField;
            }
            set
            {
                this.kLEdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.form-online.dk/")]
        public FORMdata FORMdata
        {
            get
            {
                return this.fORMdataField;
            }
            set
            {
                this.fORMdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public ProductionUnit ProductionUnit
        {
            get
            {
                return this.productionUnitField;
            }
            set
            {
                this.productionUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://www.dst.dk/da/TilSalg/Forskningsservice/Dokumentation/hoejkvalitetsvariab" +
            "le/elevregister-2/udd#")]
        public Education Education
        {
            get
            {
                return this.educationField;
            }
            set
            {
                this.educationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "https://data.gov.dk/model/core/")]
        public UnstructuredAddress UnstructuredAddress
        {
            get
            {
                return this.unstructuredAddressField;
            }
            set
            {
                this.unstructuredAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalContentData")]
        public AdditionalContentData[] AdditionalContentData
        {
            get
            {
                return this.additionalContentDataField;
            }
            set
            {
                this.additionalContentDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class CPRdata
    {

        private string cprNumberField;

        private string nameField;

        /// <remarks/>
        public string cprNumber
        {
            get
            {
                return this.cprNumberField;
            }
            set
            {
                this.cprNumberField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class CVRdata
    {

        private string cvrNumberField;

        private string companyNameField;

        /// <remarks/>
        public string cvrNumber
        {
            get
            {
                return this.cvrNumberField;
            }
            set
            {
                this.cvrNumberField = value;
            }
        }

        /// <remarks/>
        public string companyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://motorregister.skat.dk/")]
    public partial class MotorVehicle
    {

        private string licenseNumberField;

        private string chassisNumberField;

        /// <remarks/>
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }

        /// <remarks/>
        public string chassisNumber
        {
            get
            {
                return this.chassisNumberField;
            }
            set
            {
                this.chassisNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://data.gov.dk/model/core/")]
    public partial class PropertyNumber
    {

        private string propertyNumberField;

        /// <remarks/>
        public string propertyNumber
        {
            get
            {
                return this.propertyNumberField;
            }
            set
            {
                this.propertyNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class CaseID
    {

        private string caseIDField;

        private string caseSystemField;

        /// <remarks/>
        public string caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        /// <remarks/>
        public string caseSystem
        {
            get
            {
                return this.caseSystemField;
            }
            set
            {
                this.caseSystemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://kle-online.dk/")]
    public partial class KLEdata
    {

        private string subjectKeyField;

        private string versionField;

        private string activityFacetField;

        private string labelField;

        /// <remarks/>
        public string subjectKey
        {
            get
            {
                return this.subjectKeyField;
            }
            set
            {
                this.subjectKeyField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string activityFacet
        {
            get
            {
                return this.activityFacetField;
            }
            set
            {
                this.activityFacetField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.form-online.dk/")]
    public partial class FORMdata
    {

        private string taskKeyField;

        private string versionField;

        private string activityFacetField;

        private string labelField;

        /// <remarks/>
        public string taskKey
        {
            get
            {
                return this.taskKeyField;
            }
            set
            {
                this.taskKeyField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string activityFacet
        {
            get
            {
                return this.activityFacetField;
            }
            set
            {
                this.activityFacetField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.dst.dk/da/TilSalg/Forskningsservice/Dokumentation/hoejkvalitetsvariab" +
        "le/elevregister-2/udd#")]
    public partial class Education
    {

        private string educationCodeField;

        private string educationNameField;

        /// <remarks/>
        public string educationCode
        {
            get
            {
                return this.educationCodeField;
            }
            set
            {
                this.educationCodeField = value;
            }
        }

        /// <remarks/>
        public string educationName
        {
            get
            {
                return this.educationNameField;
            }
            set
            {
                this.educationNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class AdditionalContentData
    {

        private string contentDataTypeField;

        private string contentDataNameField;

        private string contentDataValueField;

        /// <remarks/>
        public string contentDataType
        {
            get
            {
                return this.contentDataTypeField;
            }
            set
            {
                this.contentDataTypeField = value;
            }
        }

        /// <remarks/>
        public string contentDataName
        {
            get
            {
                return this.contentDataNameField;
            }
            set
            {
                this.contentDataNameField = value;
            }
        }

        /// <remarks/>
        public string contentDataValue
        {
            get
            {
                return this.contentDataValueField;
            }
            set
            {
                this.contentDataValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ForwardData
    {

        private string messageUUIDField;

        private System.DateTime originalMessageDateTimeField;

        private string originalSenderField;

        private string originalContentResponsibleField;

        private string contactPointIDField;

        private string commentField;

        /// <remarks/>
        public string messageUUID
        {
            get
            {
                return this.messageUUIDField;
            }
            set
            {
                this.messageUUIDField = value;
            }
        }

        /// <remarks/>
        public System.DateTime originalMessageDateTime
        {
            get
            {
                return this.originalMessageDateTimeField;
            }
            set
            {
                this.originalMessageDateTimeField = value;
            }
        }

        /// <remarks/>
        public string originalSender
        {
            get
            {
                return this.originalSenderField;
            }
            set
            {
                this.originalSenderField = value;
            }
        }

        /// <remarks/>
        public string originalContentResponsible
        {
            get
            {
                return this.originalContentResponsibleField;
            }
            set
            {
                this.originalContentResponsibleField = value;
            }
        }

        /// <remarks/>
        public string contactPointID
        {
            get
            {
                return this.contactPointIDField;
            }
            set
            {
                this.contactPointIDField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class ReplyData
    {

        private string messageIDField;

        private string messageUUIDField;

        private string replyUUIDField;

        private string senderIDField;

        private string recipientIDField;

        private string caseIDField;

        private string contactPointIDField;

        private string generatingSystemIDField;

        private string commentField;

        private AdditionalReplyData[] additionalReplyDataField;

        /// <remarks/>
        public string messageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        public string messageUUID
        {
            get
            {
                return this.messageUUIDField;
            }
            set
            {
                this.messageUUIDField = value;
            }
        }

        /// <remarks/>
        public string replyUUID
        {
            get
            {
                return this.replyUUIDField;
            }
            set
            {
                this.replyUUIDField = value;
            }
        }

        /// <remarks/>
        public string senderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }

        /// <remarks/>
        public string recipientID
        {
            get
            {
                return this.recipientIDField;
            }
            set
            {
                this.recipientIDField = value;
            }
        }

        /// <remarks/>
        public string caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        /// <remarks/>
        public string contactPointID
        {
            get
            {
                return this.contactPointIDField;
            }
            set
            {
                this.contactPointIDField = value;
            }
        }

        /// <remarks/>
        public string generatingSystemID
        {
            get
            {
                return this.generatingSystemIDField;
            }
            set
            {
                this.generatingSystemIDField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalReplyData")]
        public AdditionalReplyData[] AdditionalReplyData
        {
            get
            {
                return this.additionalReplyDataField;
            }
            set
            {
                this.additionalReplyDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class AdditionalReplyData
    {

        private string labelField;

        private string valueField;

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class MessageBody
    {

        private string createdDateTimeField;

        private MainDocument mainDocumentField;

        private AdditionalDocument[] additionalDocumentField;

        private TechnicalDocument[] technicalDocumentField;

        /// <remarks/>
        public string createdDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }

        /// <remarks/>
        public MainDocument MainDocument
        {
            get
            {
                return this.mainDocumentField;
            }
            set
            {
                this.mainDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalDocument")]
        public AdditionalDocument[] AdditionalDocument
        {
            get
            {
                return this.additionalDocumentField;
            }
            set
            {
                this.additionalDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TechnicalDocument")]
        public TechnicalDocument[] TechnicalDocument
        {
            get
            {
                return this.technicalDocumentField;
            }
            set
            {
                this.technicalDocumentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class MainDocument
    {

        private string mainDocumentIDField;

        private string labelField;

        private File[] fileField;

        private Action[] actionField;

        /// <remarks/>
        public string mainDocumentID
        {
            get
            {
                return this.mainDocumentIDField;
            }
            set
            {
                this.mainDocumentIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public File[] File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public Action[] Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class File
    {
        public File()
        { }
        public File(string EncodingFormatField, string FilenameField, string LanguageField, byte[] ContentField)
        {
            encodingFormatField = EncodingFormatField;
            filenameField = FilenameField;
            languageField = LanguageField;
            contentField = ContentField;

        }


        private string encodingFormatField;

        private string filenameField;

        private string languageField;

        private byte[] contentField;


        /// <remarks/>
        public string encodingFormat
        {
            get
            {
                return this.encodingFormatField;
            }
            set
            {
                this.encodingFormatField = value;
            }
        }

        /// <remarks/>
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "language")]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class Action
    {

        private string labelField;

        private string actionCodeField;

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        public string actionCode
        {
            get
            {
                return this.actionCodeField;
            }
            set
            {
                this.actionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntryPoint", typeof(EntryPoint))]
        [System.Xml.Serialization.XmlElementAttribute("Reservation", typeof(Reservation))]
        [System.Xml.Serialization.XmlElementAttribute("endDateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("startDateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class EntryPoint
    {

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class Reservation
    {

        private string descriptionField;

        private string reservationUUIDField;

        private string abstractField;

        private string locationField;

        private System.DateTime startDateTimeField;

        private System.DateTime endDateTimeField;

        private string organizerMailField;

        private string organizerNameField;

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string reservationUUID
        {
            get
            {
                return this.reservationUUIDField;
            }
            set
            {
                this.reservationUUIDField = value;
            }
        }

        /// <remarks/>
        public string @abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        /// <remarks/>
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public System.DateTime startDateTime
        {
            get
            {
                return this.startDateTimeField;
            }
            set
            {
                this.startDateTimeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime endDateTime
        {
            get
            {
                return this.endDateTimeField;
            }
            set
            {
                this.endDateTimeField = value;
            }
        }

        /// <remarks/>
        public string organizerMail
        {
            get
            {
                return this.organizerMailField;
            }
            set
            {
                this.organizerMailField = value;
            }
        }

        /// <remarks/>
        public string organizerName
        {
            get
            {
                return this.organizerNameField;
            }
            set
            {
                this.organizerNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://DigitalPost.dk/MeMo-1", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        EntryPoint,

        /// <remarks/>
        Reservation,

        /// <remarks/>
        endDateTime,

        /// <remarks/>
        startDateTime,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class AdditionalDocument
    {

        private string additionalDocumentIDField;

        private string labelField;

        private File[] fileField;

        private Action[] actionField;

        /// <remarks/>
        public string additionalDocumentID
        {
            get
            {
                return this.additionalDocumentIDField;
            }
            set
            {
                this.additionalDocumentIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public File[] File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public Action[] Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://DigitalPost.dk/MeMo-1")]
    public partial class TechnicalDocument
    {

        private string technicalDocumentIDField;

        private string labelField;

        private File[] fileField;

        /// <remarks/>
        public string technicalDocumentID
        {
            get
            {
                return this.technicalDocumentIDField;
            }
            set
            {
                this.technicalDocumentIDField = value;
            }
        }

        /// <remarks/>
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public File[] File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

}